### Get User
GET /get-users HTTP/1.1
Host: localhost:8000

### Get User by Username
POST /get-user HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirsecond"
}


### Add new User
POST /add-user HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirsecond",
    "password": "password2",
    "name": "Pravir",
    "essayPrompts": []
}

### Delete all Users
DELETE /delete-users HTTP/1.1
Host: localhost:8000

### Add new Prompt
POST /user/add-prompt HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirsecond",
    "prompt": "What is your greatest weakness?",
    "college": "UCLA"
}