### Get User
GET /get-users HTTP/1.1
Host: localhost:8000

### Get User by Username
POST /get-user HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirs4"
}


### Add new User
POST /add-user HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirsecond",
    "password": "password2",
    "name": "Pravir",
    "essayPrompts": []
}

### Delete all Users
DELETE /delete-users HTTP/1.1
Host: localhost:8000

### Add new Prompt
POST /user/add-prompt HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirsecond",
    "prompt": "What is your greatest weakness?",
    "college": "UCLA"
}

### Delete Prompt based on Content
DELETE /user/remove-prompt HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "promptContent": "What is your greatest strength?",
    "username": "pravirsecond"
}

### Delete Prompt based on ID
POST /user/delete-prompt HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "promptId": "65e538a34fa08f08c73b458e",
    "username": "pravirs4"
}

### Login User with Username and Password
POST /login HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "pravirs4",
    "password": "fakepwd"
}
